Repository Devops-ohtuprojekti/DevOpsCSAOS, pull requests merged in 2021-04, with the labels that each got.

#229 Page transition animations
  end-to-end-tests/resources/survey_resource.robot
  frontend/components/contentAnimationWrapper.jsx
  frontend/components/singleQuestion.jsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.jsx
  frontend/pages/index.jsx
  frontend/pages/survey/questions/index.jsx
  frontend/pages/survey/questions/summary.jsx
  frontend/pages/survey/result.jsx
Labels: Priority 4

#294 A11y workflow
  .github/workflows/lighthouse.yml
  frontend/.eslintrc
  frontend/package-lock.json
  lighthouserc.js
Labels: accessibility (a11y), frontend

#295 Fix frontend linting in our workflow
  .github/workflows/workflow.yml
  frontend/.eslintrc
  frontend/components/button.jsx
  frontend/components/contentAnimationWrapper.jsx
  frontend/components/currently_unused/categoryResult.jsx
  frontend/components/currently_unused/totalResultBarChart.jsx
  frontend/components/currently_unused/totalResultRadarChart.jsx
  frontend/components/getDetailedResultsForm.jsx
  frontend/components/industrySelector.jsx
  frontend/components/navigationGroup.jsx
  frontend/components/option.jsx
  frontend/components/progressBar.jsx
  frontend/components/questionGrouper.jsx
  frontend/components/shared/ContentWrapper.jsx
  frontend/components/shared/InnerContentWrapper.jsx
  frontend/components/singleQuestion.jsx
  frontend/components/staticRouting.jsx
  frontend/components/totalResult.jsx
  frontend/pages/404.jsx
  frontend/pages/_app.jsx
  frontend/pages/_document.jsx
  frontend/pages/index.jsx
  frontend/pages/privacy.jsx
  frontend/pages/survey/questions/index.jsx
  frontend/pages/survey/questions/summary.jsx
  frontend/pages/survey/result.jsx
  frontend/tests/pages/Question.spec.jsx
  frontend/tests/pages/Result.spec.jsx
  frontend/tests/pages/Summary.spec.jsx
Labels: bug, configuration
