Repository Devops-ohtuprojekti/DevOpsCSAOS, pull requests merged in 2021-02, with the labels that each got.

#46 add draft style guide to documentation
  documentation/style-guide.md
Labels: documentation, project wide

#75 Frontend UI
  backend/server.js
  frontend/.babelrc
  frontend/.eslintrc
  frontend/babel.config.json
  frontend/components/button.jsx
  frontend/components/option.jsx
  frontend/components/shared/ContentWrapper.jsx
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.jsx
  frontend/pages/_document.jsx
  frontend/pages/index.jsx
  frontend/pages/survey/question/[Question].jsx
  frontend/pages/survey/questions/[questionId].jsx
  frontend/pages/survey/result.jsx
  frontend/server.js
  frontend/services/constants.js
  frontend/services/questions.js
  frontend/store.js
  frontend/styles/space.js
  frontend/tests/components/heading.spec.jsx
  frontend/tests/pages/Question.spec.jsx
  frontend/tests/testutils/themeWrapper.jsx
  package-lock.json
  package.json
Labels: Priority 1, Sprint 1

#118 Results by category frontend
  backend/config/initialData/categories.json
  backend/config/initialData/questions.json
  backend/helpers/answerResults.js
  backend/models/category.js
  backend/tests/helpers/answerResults.test.js
  frontend/components/button.jsx
  frontend/components/categoryResult.jsx
  frontend/components/progressBar.jsx
  frontend/components/shared/ContentWrapper.jsx
  frontend/components/shared/InnerContentWrapper.jsx
  frontend/components/totalResult.jsx
  frontend/pages/index.jsx
  frontend/pages/survey/contact.jsx
  frontend/pages/survey/questions/[questionId].jsx
  frontend/pages/survey/result.jsx
  frontend/store.js
  frontend/tests/components/categoryResult.spec.jsx
Labels: For Review

#108 Email validation
  frontend/components/button.jsx
  frontend/components/link.jsx
  frontend/components/progressBar.jsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/survey/contact.jsx
  frontend/store.js
  frontend/tests/pages/Contact.spec.jsx
  frontend/tests/pages/Question.spec.jsx
Labels: For Review

#132 Total results text
  backend/app.js
  backend/config/initialData/results.json
  backend/config/setupDatabase.js
  backend/controllers/results.js
  backend/models/result.js
  backend/tests/routes/results.test.js
  frontend/components/button.jsx
  frontend/components/link.jsx
  frontend/components/progressBar.jsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/survey/contact.jsx
  frontend/pages/survey/questions/[questionId].jsx
  frontend/pages/survey/questions/summary.jsx
  frontend/pages/survey/result.jsx
  frontend/services/results.js
  frontend/store.js
  frontend/tests/pages/Question.spec.jsx
Labels: For Review

#131 [WIP] UI tests refactor
  frontend/.eslintrc
  frontend/components/categoryResult.jsx
  frontend/components/totalResult.jsx
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/tests/components/categoryResult.spec.jsx
  frontend/tests/components/heading.spec.jsx
  frontend/tests/components/navigationButtons.spec.jsx
  frontend/tests/components/totalResult.spec.jsx
  frontend/tests/pages/Contact.spec.jsx
  frontend/tests/pages/Question.spec.jsx
  frontend/tests/setupAfterEnv.js
Labels: For Review, frontend, ui-testing
